var config = {
    accessToken: 'pk.eyJ1IjoiYmx1ZWNvbmR1aXQtcmFhbmFuIiwiYSI6ImNrcDQ1dmI5cTA3YWgyeHQ4eTgya3RkbmMifQ.Yy7t6IfU4KV2QTGhl91PZA',
    style: 'mapbox://styles/blueconduit-raanan/cljptmguy00w801pd21lihswy',
    alignment: 'left',
    toptitle: 'Story Map by Raanan Gurewitsch | July 2023',
    title: "Great Trees of New York Map",
    byline: 'Text by Allison C. Meier, Original map by ® Blue Crow Media 2021 (All Rights Reserved)',
    description: `The story of New York as a city begins with a tree. Beneath the boughs of a tulip tree in 1626, Dutch governor Peter Minuit is said to have made a trade with the Lenape that the colonists interpreted as the purchase of Manhattan. Even as this once forested island and the lands around it were built up, trees continued to be part of its lore as landmarks and witnesses. A monument in Prospect Park marks where a huge white oak was felled in 1776 to slow the advancing British troops; in 1792, an American sycamore shaded the founders of the New York Stock Exchange.
    <br><br>
    Some fragments of native forest survived the growth of Gotham, including the 350-year-old "Alley Pond Giant" in Queens, yet over the centuries the ecology of the city has been constantly reshaped. The international trade that made New York a metropolis brought exotics like the weeping beech from Europe and Asia's royal paulownia, whose seeds were used to pack porcelain. The city's trees are now as globally diverse as its population, from Japanese cherries that arrived by ship to towering dawn redwoods thought extinct until they were rediscovered in China in the 1940s
    <br><br>
    The city's development further changed its nature, such as the tree-moving machines of Central Park in the 19th century meticulously placing the American elms favored by Frederick Law Olmsted. In the mid 20th century, Parks Commissioner Robert Moses prolifically planted hardy London plane trees, making their distinctive peeling bark ubiquitous.
    <br><br>
    As the city expanded, greenspace was increasingly fractured, and many arboreal elders were cut down, although a few had their saviors.
    In 1969, activist Hattie Carthan, who led efforts to plant hundreds of trees in Bedford-Stuyvesant, rallied to protect a southern magnolia in danger of being bulldozed. The wizened Camperdown elm in Prospect Park was in precarious health when in 1967, Marianne Moore wrote a poem that encouraged action not just to save the tree but also to revitalize the park.
    <br><br>
    Now with extreme weather and climate change, New York's environment will again be transformed, with trees being needed more than ever for the health of the city.
    <br><br>
    The 50 trees on this map are a snapshot of the oldest, rarest, strangest, and most historic of the around 5.2 million trees in the five boroughs, where despite the dominance of concrete, an urban canopy thrives through parks, botanic gardens, cemeteries, community gardens, yards, and sidewalk tree beds.
    <br><br>
    <i>Keep scrolling to explore the Great Trees of New York Map</i>`,
    chapters: [{'id': '0',
    'title': "<a href='https://www.google.com/maps/place/40.747533,-74.005877' target='_blank'>7000 Oaks</a>",
    'image': '',
    'imageCredit': 'Various species - Chelsea, Manhattan, 10011 (A6)',
    'description': "On West 22nd Street between 10th and 11th Avenues are trees paired with basalt stone columns. Planted in 1988 by the Dia Art Foundation, they're part of Joseph Beuys's 7000 Oaks, a living artwork raising urban ecological awareness.",
    'location': {'center': [-74.005877, 40.747533],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '1',
    'title': "<a href='https://www.google.com/maps/place/40.744064,-73.744227' target='_blank'>Alley Pond Giant</a>",
    'image': '',
    'imageCredit': 'Liriodendron tulipifera - Alley Pond Park, Queens, 11364 (F3)',
    'description': "Recognized as the city's oldest tree, the Alley Pond Giant is off of East Hampton Boulevard in a dense copse in Alley Pond Park. Measured in 2000 at almost 134 feet, the tulip tree is thought to be 350 years old.",
    'location': {'center': [-73.744227, 40.744064],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '2',
    'title': "<a href='https://www.google.com/maps/place/40.707288,-73.823822' target='_blank'>American Beeches</a>",
    'image': '',
    'imageCredit': 'Fagus grandifolia - Maple Grove Cemetery, Queens, 11415 (F5)',
    'description': 'Two slender American beeches flank the lamb-shaped grave of Elisabeth Riis. They were planted by her husband -famed NYC photographer and urban reformer Jacob Riis -following her death in 1905',
    'location': {'center': [-73.823822, 40.707288],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '3',
    'title': "<a href='https://www.google.com/maps/place/40.788898,-73.955385' target='_blank'>American Elm</a>",
    'image': '',
    'imageCredit': 'Ulmus americana - Central Park, Manhattan, 10029 (B5)',
    'description': 'Near the E 97th St. entrance, this elm has a sprawling canopy of serpentine branches offering bountiful shade for visitors to the East Meadow in summer and a sculptural silhouette in winter. It is believed to be an original planting of the park.',
    'location': {'center': [-73.955385, 40.788898],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '4',
    'title': "<a href='https://www.google.com/maps/place/40.77942,-73.973267' target='_blank'>American Elm</a>",
    'image': '',
    'imageCredit': 'Ulmus americana - Central Park West, Manhattan, 10024 (B4)',
    'description': 'By the W 77th St. entrance, this elm used its ample space next to the Central Park retaining wall to flourish. Its Medusa-like branches curl in all directions above paving stones that are rippled by its shallow roots',
    'location': {'center': [-73.973267, 40.77942],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '5',
    'title': "<a href='https://www.google.com/maps/place/40.860789,-73.933607' target='_blank'>American Elm</a>",
    'image': '',
    'imageCredit': 'Ulmus americana - Fort Tryon Park, Manhattan, 10040 (A2)',
    'description': 'This old elm stands across from the Heather Garden on the Stan Michels Promenade. Walk beneath it in winter to admire its contortions, summer for a lush shade, and autumn when its leaves turn bright yellow.',
    'location': {'center': [-73.933607, 40.860789],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '6',
    'title': "<a href='https://www.google.com/maps/place/40.660627,-73.9659' target='_blank'>American Hornbeam</a>",
    'image': '',
    'imageCredit': 'Carpinus caroliniana - Prospect Park, Brooklyn, 11225 (D8)',
    'description': "This expansive American hornbeam, by the Lullwater Bridge, is one of the city's widest trees. In forests, it grows smaller as an understory tree with undulating bark that gives it the common name of musclewood.",
    'location': {'center': [-73.9659, 40.660627],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '7',
    'title': "<a href='https://www.google.com/maps/place/40.886628,-73.900731' target='_blank'>American Sycamore</a>",
    'image': '',
    'imageCredit': 'Platanus occidentalis - Kingsbridge, The Bronx, 10463 (A1)',
    'description': 'Nicknamed "the Sister Tree," this gigantic American sycamore was growing on Corlear Ave. long before the street was paved into a residential block. The sidewalk and new development jog around its V-shaped trunk. ',
    'location': {'center': [-73.900731, 40.886628],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '8',
    'title': "<a href='https://www.google.com/maps/place/40.763387,-73.824468' target='_blank'>Cedar of Lebanon</a>",
    'image': '',
    'imageCredit': 'Cedrus libani - Weeping Beech Park, Queens, 11354 (E4)',
    'description': "Now surrounded by playgrounds and concrete, this cedar of Lebanon dates to horticulturist Samuel Parsons's 19th-century nursery. A fence protects it, bordered with benches so you can sit under its umbrella of branches.",
    'location': {'center': [-73.824468, 40.763387],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '9',
    'title': "<a href='https://www.google.com/maps/place/40.668674,-73.964645' target='_blank'>Cherry Esplanade</a>",
    'image': '',
    'imageCredit': "Prunus 'Kanzan' - Brooklyn Botanic Garden, 11238 (C8)",
    'description': 'Over 200 cherry trees bloom in spring at the garden, with the Cherry Esplanade as the star attraction. From the debut of their pink flowers to the carpet of fallen petals, these cherries are a crowd-drawing sensation.',
    'location': {'center': [-73.964645, 40.668674],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '10',
    'title': "<a href='https://www.google.com/maps/place/40.627284,-74.122666' target='_blank'>The Colossus</a>",
    'image': '',
    'imageCredit': 'Liriodendron tulipifera - Clove Lakes Park, Staten Island, 10310 (A8)',
    'description': "A hulking presence near Forest Avenue in Clove Lakes Park, this 300-year-old tulip tree's trunk is more than 21 feet in circumference. Its mighty branches bloom tulip-like green-yellow flowers in spring.",
    'location': {'center': [-74.122666, 40.627284],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '11',
    'title': "<a href='https://www.google.com/maps/place/40.74010187,-73.90376412' target='_blank'>Copper Beech</a>",
    'image': '',
    'imageCredit': 'Fagus sylvatica - Woodside, Queens, 11377 (D5)',
    'description': "Surviving Woodside Avenue's transformation from rural to residential, this copper beech is at least 150 years old. Growing by an apartment complex built around its sturdy trunk, its leaves turn from purple to green in spring.",
    'location': {'center': [-73.90376412, 40.74010187],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '12',
    'title': "<a href='https://www.google.com/maps/place/40.78424069,-73.95905555' target='_blank'>English Elm</a>",
    'image': '',
    'imageCredit': 'Ulmus procera - Central Park, Manhattan, 10128 (B5)',
    'description': "In a grassy median at the Engineer's Gate, this grand English elm lifts its big branches as if welcoming visitors to Central Park. Mature examples like this are scarce as they were devastated by Dutch elm disease.",
    'location': {'center': [-73.95905555, 40.78424069],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '13',
    'title': "<a href='https://www.google.com/maps/place/40.73414154,-73.9839349' target='_blank'>English Elm</a>",
    'image': '',
    'imageCredit': 'Ulmus procera - Stuyvesant Square Park, 10003 (B6)',
    'description': 'This English elm dates to an 1836 gift by descendants of Peter Stuyvesant- last Director-General of New Netherlands-of 4 acres of their farm. It towers in the northwestern corner, a fence curving around its brawny roots.',
    'location': {'center': [-73.9839349, 40.73414154],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '14',
    'title': "<a href='https://www.google.com/maps/place/40.86841461,-73.91911506' target='_blank'>Ginkgo</a>",
    'image': '',
    'imageCredit': 'Ginkgo biloba - Isham Park, Manhattan, 10034 (A2)',
    'description': 'A historic mile marker is embedded in the wall below this colossal Ginkgo, another vestige of centuries of change. Located just inside Isham Park, the tree is especially gorgeous in its golden autumn color.',
    'location': {'center': [-73.91911506, 40.86841461],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '15',
    'title': "<a href='https://www.google.com/maps/place/40.77476076,-73.76742726' target='_blank'>Ginkgo</a>",
    'image': '',
    'imageCredit': 'Ginkgo biloba - Crocheron Park, Queens, 11360 (F3)',
    'description': 'The "Boss Tweed Ginkgo" witnessed the flight of corrupt politician William M. Tweed to the Crocheron House Hotel. The hotel burned down in 1908; the majestic Ginkgo endures in today\'s Crocheron Park.',
    'location': {'center': [-73.76742726, 40.77476076],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '16',
    'title': "<a href='https://www.google.com/maps/place/40.73202884,-73.99853222' target='_blank'>Hangman's Elm</a>",
    'image': '',
    'imageCredit': 'Ulmus procera - Washington Square Park, 10012 (B6)',
    'description': "There are no reports of anyone hanged from this English elm, yet the legend persists. As Manhattan's oldest tree, it has witnessed three centuries, including the park's grim period when it was a potter's field.",
    'location': {'center': [-73.99853222, 40.73202884],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '17',
    'title': "<a href='https://www.google.com/maps/place/40.72605563,-73.98199456' target='_blank'>Hare Krishna Tree</a>",
    'image': '',
    'imageCredit': 'Ulmus americana - Tompkins Square Park, 10009 (B6)',
    'description': 'In 1966, the "Hare Krishna" mantra was chanted for the first time outside India, below this American elm in Tompkins Square Park, sparkling the spiritual movement in the US. Devotees periodically return to wrap its trunk in garlands.',
    'location': {'center': [-73.98199456, 40.72605563],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '18',
    'title': "<a href='https://www.google.com/maps/place/40.660579,-73.965347' target='_blank'>Japanese Pagoda Tree</a>",
    'image': '',
    'imageCredit': 'Styphnolobium japonicum - Prospect Park, Brooklyn, 11225 (D8)',
    'description': "Park visitors enjoy climbing the branches of this imposing Japanese pagoda tree. Despite the name, it's from China, with its tolerance of city life and panicles of white flowers making it a popular street tree.",
    'location': {'center': [-73.965347, 40.660579],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '19',
    'title': "<a href='https://www.google.com/maps/place/40.78893,-73.9577' target='_blank'>London Plane</a>",
    'image': '',
    'imageCredit': 'Platanus × acerifolia - Central Park Bridle Path, 10128 (B4)',
    'description': "The NYC Parks logo is apocryphally based on the leaf of the London plane, fitting as the resilient urban tree is ubiquitous in the city. This multi-trunked example on the Bridle Path is one of Central Park's oldest.",
    'location': {'center': [-73.9577, 40.78893],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '20',
    'title': "<a href='https://www.google.com/maps/place/40.74176185,-73.9877348' target='_blank'>The Madison Tree</a>",
    'image': '',
    'imageCredit': 'Quercus rubra - Madison Square Park, Manhattan, 10010 (B6)',
    'description': "A tree from the Virginia estate of the park's namesake -President James Madison - was dedicated here in 1936. The fast-growing red oak stands tall on Madison Avenue, a plaque recalling its provenance.",
    'location': {'center': [-73.9877348, 40.74176185],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '21',
    'title': "<a href='https://www.google.com/maps/place/40.74778777,-73.80897096' target='_blank'>Manchurian Linden</a>",
    'image': '',
    'imageCredit': 'Tilia mandshurica - Kissena Park, Queens, 11355 (F4)',
    'description': 'The Parsons nursery which introduced rare specimens from around the world to the US became part of Kissena Park in the early 1900s. A grove of its trees includes this huge Manchurian linden by the tennis courts.',
    'location': {'center': [-73.80897096, 40.74778777],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '22',
    'title': "<a href='https://www.google.com/maps/place/40.74778777,-73.80897096' target='_blank'>Persian Parrotia</a>",
    'image': '',
    'imageCredit': 'Parrotia persica - Kissena Park, Queens, 11355 (F4)',
    'description': 'South of the comfort station, this rare Persian parrotia from Iran is one of the over 100 tree varieties in Kissena Park, remnants of the 19th-century Parsons nursery from when Queens was an American horticulture hub. Visit in fall for its fiery foliage.',
    'location': {'center': [-73.80897096, 40.74778777],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '23',
    'title': "<a href='https://www.google.com/maps/place/40.66077021,-73.9693696' target='_blank'>Osage Orange</a>",
    'image': '',
    'imageCredit': 'Maclura pomifera - Prospect Park, Brooklyn 11225 (C8)',
    'description': 'South of the Nethermead Arches, this Osage orange with two crooked trunks braced by metal bars drops softball-sized fruit in fall. Prospect Park designer Frederick Law Olmsted favored the Midwestern tree and cultivated them at his Staten Island home.',
    'location': {'center': [-73.9693696, 40.66077021],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '24',
    'title': "<a href='https://www.google.com/maps/place/40.70223108,-73.84300877' target='_blank'>Pine Grove</a>",
    'image': '',
    'imageCredit': 'Pinus strobus - Forest Park, Queens, 11418 (F5)',
    'description': 'After chestnut blight ravaged Forest Park, this Pine Grove was planted in 1914 as a tribute to military veterans. The atmospheric stand of mostly Eastern white pines was recently expanded with hundreds of new saplings.',
    'location': {'center': [-73.84300877, 40.70223108],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '25',
    'title': "<a href='https://www.google.com/maps/place/40.86110901,-73.87390599' target='_blank'>Royal Paulownia</a>",
    'image': '',
    'imageCredit': 'Paulownia tomentosa - New York Botanical Garden, The Bronx (B2)',
    'description': 'Celebrated in China for its purple flowers, the royal paulownia is considered invasive in the US. They are common street flora; few grow into stunning examples like this one on a hill in the botanical garden.',
    'location': {'center': [-73.87390599, 40.86110901],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '26',
    'title': "<a href='https://www.google.com/maps/place/40.73187535,-74.00691312' target='_blank'>Silver Maples</a>",
    'image': '',
    'imageCredit': 'Acer saccharinum - St. Luke in the Fields, Manhattan, 10014 (B6)',
    'description': 'The Saint Luke in the Fields gardens are hidden gems of the West Village with these two centenarian silver maples found in the North Garden. They gracefully grow over what was once a church burial ground.',
    'location': {'center': [-74.00691312, 40.73187535],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '27',
    'title': "<a href='https://www.google.com/maps/place/40.85710575,-73.87646262' target='_blank'>Snake Branch Spruce</a>",
    'image': '',
    'imageCredit': "Picea abies 'Virgata' - New York Botanical Garden, The Bronx (B2)",
    'description': 'With its cascade of pendulous branchlets, the snake branch spruce stands out in the Benenson Ornamental Conifer Collection. It was planted in the 1940s by Marian Cruger Coffin, one of the first women landscape architects.',
    'location': {'center': [-73.87646262, 40.85710575],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '28',
    'title': "<a href='https://www.google.com/maps/place/40.69070434,-73.94692421' target='_blank'>Southern Magnolia</a>",
    'image': '',
    'imageCredit': 'Magnolia grandiflora - Magnolia Tree Earth Center, Brooklyn (D7)',
    'description': "A Southern magnolia planted in 1885 is NYC's sole living thing designated a city landmark. It was saved in the 1960s by activist Hattie Carthan who is remembered in a mural by the tree, her face emerging from its branches, on Lafayette Avenue.",
    'location': {'center': [-73.94692421, 40.69070434],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '29',
    'title': "<a href='https://www.google.com/maps/place/40.89976651,-73.9123365' target='_blank'>Sugar Maple</a>",
    'image': '',
    'imageCredit': 'Acer saccharum - Wave Hill, The Bronx, 10471 (A1)',
    'description': "At the top of Wave Hill's lawn is a lofty sugar maple dating to the 19th century. A bench below it offers a restful vista of the garden which in years past has hosted maple sap tapping demonstrations.",
    'location': {'center': [-73.9123365, 40.89976651],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '30',
    'title': "<a href='https://www.google.com/maps/place/40.71118202,-74.01351897' target='_blank'>The Survivor Tree</a>",
    'image': '',
    'imageCredit': 'Pyrus calleryana - 9/11 Memorial, Manhattan, 10007 (B7)',
    'description': "Pulled from the Ground Zero rubble, this Callery pear was nursed back to health by NYC Parks. Replanted at the 9/11 Memorial in 2010, it's a symbol of resilience, with new branches thriving alongside its scars.",
    'location': {'center': [-74.01351897, 40.71118202],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '31',
    'title': "<a href='https://www.google.com/maps/place/40.83330685,-73.85239734' target='_blank'>Sweetgum</a>",
    'image': '',
    'imageCredit': 'Liquidambar styraciflua - Parkchester, The Bronx, 10462 (C2)',
    'description': 'Soaring up from the yard of the American Legion Post on Newbold Avenue is this veteran sweetgum. The southern tree has spiky seed pods and star-shaped leaves that turn yellow, red, and purple in fall.',
    'location': {'center': [-73.85239734, 40.83330685],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '32',
    'title': "<a href='https://www.google.com/maps/place/40.68379948,-74.00339918' target='_blank'>Timecast Tree Shadows</a>",
    'image': '',
    'imageCredit': 'Various species - Columbia Street Waterfront Dist., 11201 (B8)',
    'description': 'Artist Nobuho Nagasawa immortalized the shadows of six street trees -all NY natives- on the Columbia Street sidewalk. Dedicated in 2012, the installation captures a fleeting moment in time as the trees grow, change, or die.',
    'location': {'center': [-74.00339918, 40.68379948],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '33',
    'title': "<a href='https://www.google.com/maps/place/40.65316497,-73.98863348' target='_blank'>Weeping Beech</a>",
    'image': '',
    'imageCredit': "Fagus sylvatica 'Pendula' - Green-Wood Cemetery, Brooklyn, 11218 (C8)",
    'description': "In summer the pendulous branches of this weeping beech create a verdant tunnel on Larch Avenue. It's only one of the many magnificent trees in Green-Wood Cemetery, an arboretum with hundreds of species.",
    'location': {'center': [-73.98863348, 40.65316497],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '34',
    'title': "<a href='https://www.google.com/maps/place/40.89073713,-73.87074245' target='_blank'>Weeping Beech</a>",
    'image': '',
    'imageCredit': "Fagus sylvatica 'Pendula' - Woodlawn Cemetery, The Bronx, 10470 (B1)",
    'description': "Overshadowing the temple mausoleum of robber baron Jay Gould is what's cited as NYC's biggest weeping beech. From outside it's a monster of veiled branches; step inside to appreciate the structure of its elephantine trunk.",
    'location': {'center': [-73.87074245, 40.89073713],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '35',
    'title': "<a href='https://www.google.com/maps/place/40.763387,-73.824468' target='_blank'>Weeping Beeches</a>",
    'image': '',
    'imageCredit': "Fagus sylvatica 'Pendula' - Weeping Beech Park, Queens, 11354 (E4)",
    'description': 'A 1998 funeral mourned the death of a weeping beech that arrived from Belgium in a flower pot in 1847. Its offspring circle where the living city landmark -one of the first weeping beeches in the US-stood for 150 years.',
    'location': {'center': [-73.824468, 40.763387],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '36',
    'title': "<a href='https://www.google.com/maps/place/40.89163487,-73.89038147' target='_blank'>White Ash</a>",
    'image': '',
    'imageCredit': 'Fraxinus americana - Van Cortlandt Park, The Bronx, 10471 (B1)',
    'description': "At the southeast corner of the Van Cortlandt Park Parade Ground resides a stout white ash. Look for a miniature of the massive tree nearby: it's part of the NYC Historic Great Tree Cloning Project.",
    'location': {'center': [-73.89038147, 40.89163487],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '37',
    'title': "<a href='https://www.google.com/maps/place/40.89590227,-73.86776095' target='_blank'>White Oak</a>",
    'image': '',
    'imageCredit': 'Quercus alba - Woodlawn Cemetery, The Bronx, 10470 (B1)',
    'description': 'The broad branches of this venerable white oak stretch over the graves on the northern edge of Woodlawn Cemetery. Likely predating the 19th-century burial ground, the tree turns a brilliant orange-red in fall.',
    'location': {'center': [-73.86776095, 40.89590227],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '38',
    'title': "<a href='https://www.google.com/maps/place/40.78296981,-73.95996625' target='_blank'>Yoshino Cherry Trees</a>",
    'image': '',
    'imageCredit': 'Prunus × yedoensis - Central Park Reservoir, Manhattan, 10128 (B5)',
    'description': "The Yoshino cherry grove on the Reservoir's east side was planted in 1912 as a gift from Japan. Although many trees were replaced over the years, a few centenarians still grow with gnarled trunks and pale pink flowers.",
    'location': {'center': [-73.95996625, 40.78296981],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '39',
    'title': "<a href='https://www.google.com/maps/place/40.8127393,-73.96226526' target='_blank'>Yoshino Cherry Trees</a>",
    'image': '',
    'imageCredit': 'Prunus x yedoensis - Sakura Park, Manhattan, 10027 (A4)',
    'description': "Yoshino cherries from Japan were to arrive for the 300th anniversary of Henry Hudson's voyage to NYC but were lost at sea. New cherries made it in 1912 and their planting included this charming park renamed in their honor.",
    'location': {'center': [-73.96226526, 40.8127393],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '40',
    'title': "<a href='https://www.google.com/maps/place/40.7833577,-73.9666817' target='_blank'>Arthur Ross Pinetum</a>",
    'image': '',
    'imageCredit': 'Various species - Central Park, Manhattan, 10024 (B5)',
    'description': 'This 4-acre pinetum spearheaded in the 1970s by philanthropist Arthur Ross was inspired by an evergreen grove originally planned for Central Park. It has over 600 trees from across the globe, from the Alps to the Himalayas.',
    'location': {'center': [-73.9666817, 40.7833577],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '41',
    'title': "<a href='https://www.google.com/maps/place/40.77581601,-73.93568851' target='_blank'>Auto Body Shop Tree</a>",
    'image': '',
    'imageCredit': 'Fraxinus pennsylvanica - 1-0927th Avenue, Astoria, Queens, 11102 (B5)',
    'description': 'Countless great trees have been lost to new construction; the Cove Auto Care office was built around the trunk of this specimen. The crown of this ash bursts through its roof, happily coexisting with the business below.',
    'location': {'center': [-73.93568851, 40.77581601],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '42',
    'title': "<a href='https://www.google.com/maps/place/40.77787184,-73.96970423' target='_blank'>Black Tupelo</a>",
    'image': '',
    'imageCredit': 'Nyssa sylvatica - Central Park Ramble, Manhattan, 10024 (B5)',
    'description': "Presiding over a meadow, a two minutes stroll south of Belvedere Castle, this black tupelo is believed to have been present at Central Park's 1858 opening. While its three trunks are striking year-round, in fall it shows off with blazing scarlet foliage.",
    'location': {'center': [-73.96970423, 40.77787184],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '43',
    'title': "<a href='https://www.google.com/maps/place/40.6605003,-73.96551302' target='_blank'>Camperdown Elm</a>",
    'image': '',
    'imageCredit': "Ulmus glabra 'Camperdownil' - Prospect Park, Brooklyn, 11225 (D8)",
    'description': 'This twisty tree was declared "Brooklyn\'s crowning curio" by poet Marianne Moore who led its 1960s preservation. Just south of the boathouse, it is one of the country\'s oldest Camperdown elms. All examples of this tree are grafted onto other elm species that support their weeping branches.',
    'location': {'center': [-73.96551302, 40.6605003],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '44',
    'title': "<a href='https://www.google.com/maps/place/40.66666489,-73.96441737' target='_blank'>Caucasian Wingnut</a>",
    'image': '',
    'imageCredit': 'Pterocarya fraxinifolio - Brooklyn Botanic Garden, 11238 (D8)',
    'description': 'The Caucasian wingnut is named for its originating home of the Caucasus and its winged fruit. The garden planted it as a sapling in 1922 and after almost a century, it has one of the largest trunks in the city.',
    'location': {'center': [-73.96441737, 40.66666489],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '45',
    'title': "<a href='https://www.google.com/maps/place/40.79333022,-73.97827626' target='_blank'>Crabapple Grove</a>",
    'image': '',
    'imageCredit': 'Malus spp. - Riverside Park, Manhattan, 10024 (A5)',
    'description': 'The sign says "Garden for All Seasons" but the 4-acre Crabapple Grove stuns in spring. Its blooms range from luminous white to radiant pink with new plantings and knotty heritage trees dating to a 1930s overhaul of the park.',
    'location': {'center': [-73.97827626, 40.79333022],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '46',
    'title': "<a href='https://www.google.com/maps/place/40.69662094,-73.99605951' target='_blank'>Dawn Redwood</a>",
    'image': '',
    'imageCredit': 'Metasequoia glyptostroboides - Willow Street, Brooklyn, 11201 (B7)',
    'description': 'Thought extinct until it was rediscovered in China in the 1940s, the dawn redwood is now a popular street tree. A skyscraper of the urban forest, one looms over the historic architecture on the south end of Willow St.',
    'location': {'center': [-73.99605951, 40.69662094],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '47',
    'title': "<a href='https://www.google.com/maps/place/40.72408081,-73.99185047' target='_blank'>Dawn Redwood</a>",
    'image': '',
    'imageCredit': 'Metasequoia glyptostroboides - Liz Christy Community Garden, 10003 (B7)',
    'description': "One of the city's tallest dawn redwoods roots in this pioneering greenspace on East Houston Street. The first NYC community garden, it was established in 1973 when Liz Christy and the Green Guerillas reclaimed a derelict lot as a green oasis.",
    'location': {'center': [-73.99185047, 40.72408081],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true},
   {'id': '48',
    'title': "<a href='https://www.google.com/maps/place/40.83707716,-73.93996766' target='_blank'>The Dinosaur</a>",
    'image': '',
    'imageCredit': 'Ulmus procera - St Nicholas Avenue & W 163rd St., 10032 (A3)',
    'description': 'City lore says that George Washington passed beneath this English elm in 1776 as the British-occupied city burned. Called "The Dinosaur," it was surveyed in the recent street tree census at 60 inches in diameter, making it Manhattan\'s largest street tree.',
    'location': {'center': [-73.93996766, 40.83707716],
     'zoom': 15,
     'pitch': 0,
     'bearing': 0},
    'showMarkers': true}]
};
